---
- name: copy backend files to server #1
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: False
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
   - deploy