---
- name: Exercise #1
  hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: False
  tasks:
    - name: "install apache 2."
      become: true
      apt:
        name: ["apache2"]
        state: latest
        update_cache: yes


