- name: Creates directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
- name: "move backend files to server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu
    mode: '0777'


- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    npm install
    pm2 start npm -- run "start:dev"
